/**
 * 
 */
package ippoz.reload.commons.algorithm;

/**
 * @author Tommy
 *
 */
public enum AlgorithmType {
	
	HBOS, DBSCAN, LDCOF_KMEANS, LDCOF_DBSCAN, SDO, SOM, FASTVOA,
	
	ELKI_KMEANS, ELKI_GMEANS, ELKI_ABOD, ELKI_FASTABOD, ELKI_LOF, ELKI_COF, ELKI_ODIN, ELKI_SVM, ELKI_KNN, ELKI_SOS, ELKI_ISOS,
	
	WEKA_ISOLATIONFOREST,
	
	SLIDING_SPS,
	
	SLIDING_ELKI_COF, SLIDING_ELKI_CLUSTERING, SLIDING_ELKI_KNN, SLIDING_ELKI_ABOD,
	
	SLIDING_WEKA_ISOLATIONFOREST   
	
}
